### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by coding-in-public**
You may want to change the wording of the page, but hopefully the functionality looks good! As always, feel free to take or leave anything.

### CODE REVIEW

**Comment by coding-in-public** [comment]
Oh, and I would be interested on the commits. Is this more in the right direction?

**Comment by jsjoeio** [comment]
Yes, exactly! Way easier to see the chunks and how this all came together :D 

nit: I prefer when the first word is not capitalized but that's more a personal style 🤣 

Overall, nice work man! Thanks for adding this!

**Comment by jsjoeio** [comment]
Oh and I don't know if you knew this but you can tie PRs to issues and have them autoclose when the PR merges by using special keywords like "fixes"

Fixes https://github.com/jsjoeio/speak-argentinian-spanish/issues/14

**Comment by coding-in-public** [comment]
I didn't actually know that about the Fixes, etc. Thanks!

**Pull request merged**
