### PR TITLE
Fancy footer

### LINKED ISSUE #12: Add fancy footer
## Context

I want to add a fancy footer to the bottom where I can link to other pages and also give credit to the people who helped build the site (Tad/Chris and [Tony](https://www.youtube.com/c/TonyBalDev)).

### Inspiration

image

image

### Notes

> hm yeah if you want to mention my name and a backlink to tadscritchfield.com that would be cool. and yeah any twitter stuff would help too
- from Tad

### PR DESCRIPTION
**Pull request by coding-in-public**
Quick job, but hopefully this mostly works :)

Fixes #12

### CODE REVIEW

**Comment by coding-in-public** [comment]
@jsjoeio, also I should mention that it looks like we’re using Ranade Medium, but it looks like you’d like a lighter version. Want me to move the body font to Ranade Regular? (it’s slightly smaller)

**Review by jsjoeio — CHANGES_REQUESTED** [review]
> also I should mention that it looks like we’re using Ranade Medium, but it looks like you’d like a lighter version. Want me to move the body font to Ranade Regular? (it’s slightly lighter)

If that's easy to do, yes please :D 

Sidenote: I checked the preview and I don't see the new footer on the home page, only on the other pages (looks incredible!)

image

Can we add to the home page?

**Comment by coding-in-public** [comment]
@jsjoeio Hey, yeah! I'll get that typeface updated. For the homepage, I actually removed the new footer because the layout needs to be adjusted more broadly to include it. I'm happy to come up with a refactored homepage, too, but also happy to put that into a new branch if that's better? For now I'll change out the typeface.

**Comment by jsjoeio** [comment]
> For the homepage, I actually removed the new footer because the layout needs to be adjusted more broadly to include it. I'm happy to come up with a refactored homepage, too, but also happy to put that into a new branch if that's better?

Ah gotcha!! Sure that works, I'll merge this one then we can do the refactor + footer on homepage in separate PR! 🚀

**Review by jsjoeio — APPROVED** [review]

**Pull request merged**
